apiVersion: v1
kind: Service
metadata:
 name: express-app-service
 labels:
    app: express-app
spec:
 type: NodePort
 ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000 # [!] depending on platform and vm and ... the port might be assigned at random so check it using kubectl get services and look for external; ip
 selector:
    app: express-app
