
# Start with the official Python 3.10 image from Docker Hub
FROM python:3.10-slim


# Set the working directory in the container
WORKDIR /app

# Copy requirements file to the container
COPY requirements.txt /app/

# Install dependencies
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copy the application code to the container
COPY . /app/
EXPOSE 5000
# Specify the default command to run the application
CMD ["python", "server/main.py"]

