# Use an official Python runtime as the base image
FROM python

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed dependencies specified in requirements.txt
RUN pip  install -r requirements.txt

# Expose the port your app runs on (if applicable)
EXPOSE 5000

# Define the command to run your app using Python
CMD ["python", "menu/main.py"]
