FROM node:14

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

RUN npx prisma generate

EXPOSE 3001

ENV NODE_ENV production

CMD ["npm", "run", "start_ts_dev"]
