# Use the official Node.js 14 image as the base image
FROM node:alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Build the Prisma schema
RUN npx prisma generate

# Expose any necessary ports (replace 4000 with the actual port your app uses)
EXPOSE 4000

# Command to run the application
CMD ["npm", "start"]
