# # Stage 1: Build environment
# FROM node:alpine AS build

# # Set working directory
# WORKDIR /usr/src/app

# # Copy package.json and package-lock.json
# COPY package*.json ./

# # Install dependencies
# RUN npm install

# # Copy the rest of the application code
# COPY . .

# # Build TypeScript to JavaScript
# RUN npm run build

# # Stage 2: Production environment
# FROM node:14-alpine

# # Set working directory
# WORKDIR /usr/src/app

# # Copy built JavaScript files and package.json
# COPY --from=build /usr/src/app/dist ./dist
# COPY --from=build /usr/src/app/package*.json ./

# # Install only production dependencies
# RUN npm install --production

# # Expose port
# EXPOSE 8080

# # Start the server
# CMD ["node", "dist/index.js"]
# TODO fix this ^



FROM node:alpine

COPY . . 

RUN npm install 

CMD ["npm","run","start_ts_dev"]



