apiVersion: v1
kind: Service
metadata:
 name: {{ .Values.serviceName }}-service
spec:
 type: LoadBalancer
 ports:
 - port: 80
    targetPort: {{ .Values.containerPort }}
    protocol: TCP
 selector:
    app: {{ .Values.serviceName }}
